FROM golang:alpine as build

WORKDIR /go/src/app

COPY . .

RUN CGO_ENABLED=0 go install -ldflags '-extldflags "-static"' -tags timetzdata ./local/

FROM scratch

COPY --from=build /go/bin/local /local
COPY --from=alpine:latest /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs

ENTRYPOINT ["/local"]
