version: "3"
services:
  pebble:
    image: letsencrypt/pebble
    ports:
      - "14000:14000"
      - "15000:15000"
  gin:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "5001:5001"
      - "5002:5002"
    networks:
      default:
        aliases:
          - www.gin.com
          - www.tonic.com
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
